apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-service
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-app-pod
  ports:
    - port: 8081
      protocol: "TCP"
      nodePort: 30002
      targetPort: 8081
