apiVersion: v1
kind: Service
metadata:
  name: resources-db-service
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: resources-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: resources-db
  serviceName: resources-db-service
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-pg-container
          image: postgres:17
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: resources-config
                  key: RESOURCES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: resources-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resources-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: resources-config
                  key: RESOURCES_DB_PORT
          ports:
            - containerPort: 5432
              name: resources-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: resources-db-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 3
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: init-sql
          configMap:
            name: resources-config
            items:
              - key: init.sql
                path: init.sql
  volumeClaimTemplates:
    - metadata:
        name: resources-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi