apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-config
  namespace: {{ .Values.namespace }}
data:
  RESOURCES_MS_PORT: "8080"
  RESOURCES_DB_URL: "resources-db-service.{{ .Values.namespace }}.svc.cluster.local"
  RESOURCES_DB_PORT: "5432"
  RESOURCES_DB: "resources_db"
  init.sql: |
   CREATE TABLE IF NOT EXISTS resources (
       id SERIAL PRIMARY KEY,
       blob bytes
   );

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-config
  namespace: {{ .Values.namespace }}
data:
  SONGS_MS_PORT: "8081"
  SONGS_DB_URL: "songs-db-service.{{ .Values.namespace }}.svc.cluster.local"
  SONGS_DB_PORT: "5432"
  SONGS_DB: "songs_db"
  init.sql: |
   CREATE TABLE IF NOT EXISTS songs (
       id SERIAL PRIMARY KEY,
       name text,
       artist text,
       album text,
       length text,
       resource_id int,
       year text
   );
