apiVersion: v1
kind: Secret
metadata:
  name: resources-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded 'postgres'
---
apiVersion: v1
kind: Secret
metadata:
  name: songs-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded 'postgres'