apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: resources-service
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: songs-app-pod
  ports:
    - port: 8081
      protocol: "TCP"
      targetPort: 8081
